<?php

declare(strict_types=1);

return [
    'locale' => 'de-DE',
    'html_lang' => 'de-DE',
    'date_template' => '{day}. {month} {year} um {time}',
    'months' => [
        1 => 'Januar',
        2 => 'Februar',
        3 => 'März',
        4 => 'April',
        5 => 'Mai',
        6 => 'Juni',
        7 => 'Juli',
        8 => 'August',
        9 => 'September',
        10 => 'Oktober',
        11 => 'November',
        12 => 'Dezember',
    ],
    'duration_zero' => '0 Sekunden',
    'duration_pair_glue' => ' und ',
    'duration_middle_glue' => ', ',
    'duration_last_glue' => ' und ',
    'duration_units' => [
        'year' => ['one' => 'Jahr', 'other' => 'Jahre'],
        'month' => ['one' => 'Monat', 'other' => 'Monate'],
        'week' => ['one' => 'Woche', 'other' => 'Wochen'],
        'day' => ['one' => 'Tag', 'other' => 'Tage'],
        'hour' => ['one' => 'Stunde', 'other' => 'Stunden'],
        'minute' => ['one' => 'Minute', 'other' => 'Minuten'],
        'second' => ['one' => 'Sekunde', 'other' => 'Sekunden'],
    ],
    'texts' => [
        'page_neutral_title' => 'Diese Seite ist nicht verfügbar.',
        'page_neutral_heading' => 'Diese Seite ist nicht verfügbar.',
        'page_neutral_body_1' => 'Über diese URL werden keine weiteren Informationen angezeigt.',
        'page_neutral_body_2' => 'Sie können diese Seite nun schließen.',
        'page_confirm_title' => 'Noch am Leben?',
        'page_confirm_heading' => 'Bitte melden…',
        'page_confirm_intro' => 'Wenn alles in Ordnung ist, bitte den Button anklicken.',
        'page_confirm_button' => 'Alles in Ordnung!',
        'page_confirm_ok_title' => 'Bestätigung gespeichert.',
        'page_confirm_ok_heading' => 'Danke.',
        'page_confirm_ok_intro' => 'Der Zyklus wurde neu gestartet…',
        'page_confirm_ok_details_heading' => 'Wie es jetzt weitergeht:',
        'page_ack_ok_title' => 'Rückmeldung gespeichert.',
        'page_ack_ok_heading' => 'Danke.',
        'page_ack_ok_body_1' => 'Die Nachricht wurde als erhalten bestätigt.',
        'page_ack_ok_body_2' => 'Sie werden keine weiteren E-Mails mehr erhalten. Der Totmannschalter wurde stillgelegt.',
        'page_ack_ok_body_3' => 'Bitte folgen Sie nun den Wünschen und Hinweisen in der empfangenen E-Mail.',
        'page_ack_ok_body_4' => 'Wichtig! Sollte die E-Mail einen Downloadlink enthalten haben, stellen Sie sicher, dass Sie dieses Dokument heruntergeladen haben.',
        'page_error_title' => 'Das hat gerade nicht geklappt.',
        'page_error_heading' => 'Das hat gerade nicht geklappt.',
        'page_error_body_1' => 'Bitte versuchen Sie es noch einmal.',
        'page_error_body_2' => 'Falls das Problem bestehen bleibt, bewahren Sie die ursprüngliche Nachricht bitte auf, damit der Absender oder Betreiber den Fall prüfen kann.',
        'page_error_code_label' => 'Referenzcode',
        'page_download_unavailable_title' => 'Diese URL ist nicht gültig.',
        'page_download_unavailable_heading' => 'Diese URL ist nicht gültig.',
        'page_download_unavailable_body_1' => 'Der Link zu diesem Download ist entweder abgelaufen oder nicht mehr gültig.',
        'page_download_unavailable_body_2' => 'Bitte behalten Sie die ursprüngliche Nachricht und versuchen Sie es später noch einmal, falls der Link noch gültig sein sollte…',
        'page_download_unavailable_body_3' => '',
        'detail_cycle_started' => 'Der aktuelle Zyklus begann am {datetime}.',
        'detail_last_confirm' => 'Die letzte erfolgreiche Bestätigung wurde am {datetime} gespeichert.',
        'detail_window_opens' => 'Das Bestätigungsfenster öffnet sich am {datetime}.',
        'detail_deadline' => 'Die Bestätigungsfrist für diesen Zyklus endet am {datetime}.',
        'detail_next_reminder' => 'Die nächste Erinnerung ist für {datetime} vorgesehen.',
        'detail_window_opens_after' => '{duration} bis sich das Bestätigungsfenster öffnet.',
        'detail_window_length' => '{duration} Dauer des Bestätigungsfensters.',
        'detail_reminders_repeat' => 'Während das Fenster geöffnet ist, werden Erinnerungen alle {duration} wiederholt.',
        'detail_grace' => 'Nach der Frist gilt zusätzlich eine Karenzzeit von {duration}, bevor eine Eskalation in Betracht gezogen wird.',
        'detail_missed_required_one' => '1 verpasster Zyklus ist erforderlich, bevor eine Eskalation ausgelöst werden kann.',
        'detail_missed_required_other' => '{count} verpasste Zyklen sind erforderlich, bevor eine Eskalation ausgelöst werden kann.',
        'detail_missed_current_zero' => 'Aktuell sind keine verpassten Zyklen gespeichert.',
        'detail_missed_current_one' => 'Aktuell ist 1 verpasster Zyklus gespeichert.',
        'detail_missed_current_other' => 'Aktuell sind {count} verpasste Zyklen gespeichert.',
    ],
];
