<?php

declare(strict_types=1);

return [
    'locale' => 'en-GB',
    'html_lang' => 'en-GB',
    'date_template' => '{day} {month} {year} at {time}',
    'months' => [
        1 => 'January',
        2 => 'February',
        3 => 'March',
        4 => 'April',
        5 => 'May',
        6 => 'June',
        7 => 'July',
        8 => 'August',
        9 => 'September',
        10 => 'October',
        11 => 'November',
        12 => 'December',
    ],
    'duration_zero' => '0 seconds',
    'duration_pair_glue' => ' and ',
    'duration_middle_glue' => ', ',
    'duration_last_glue' => ' and ',
    'duration_units' => [
        'year' => ['one' => 'year', 'other' => 'years'],
        'month' => ['one' => 'month', 'other' => 'months'],
        'week' => ['one' => 'week', 'other' => 'weeks'],
        'day' => ['one' => 'day', 'other' => 'days'],
        'hour' => ['one' => 'hour', 'other' => 'hours'],
        'minute' => ['one' => 'minute', 'other' => 'minutes'],
        'second' => ['one' => 'second', 'other' => 'seconds'],
    ],
    'texts' => [
        'page_neutral_title' => 'This page is not available.',
        'page_neutral_heading' => 'This page is not available.',
        'page_neutral_body_1' => 'No further information is shown through this URL.',
        'page_neutral_body_2' => 'You may close this page now.',
        'page_confirm_title' => 'Still alive?',
        'page_confirm_heading' => 'Please check in…',
        'page_confirm_intro' => 'If all is well, please click the button below.',
        'page_confirm_button' => 'Everything is okay!',
        'page_confirm_ok_title' => 'Confirmation saved.',
        'page_confirm_ok_heading' => 'Thank you.',
        'page_confirm_ok_intro' => 'The cycle has been reset…',
        'page_confirm_ok_details_heading' => 'What happens next:',
        'page_ack_ok_title' => 'Acknowledgement saved.',
        'page_ack_ok_heading' => 'Thank you.',
        'page_ack_ok_body_1' => 'The message has been marked as received.',
        'page_ack_ok_body_2' => 'You will not receive any further emails. The dead man’s switch has been shut down.',
        'page_ack_ok_body_3' => 'Please now follow the wishes and instructions in the email you received.',
        'page_ack_ok_body_4' => 'Important! If the email included a download link, make sure that you have downloaded that document.',
        'page_error_title' => 'That did not work just now.',
        'page_error_heading' => 'That did not work just now.',
        'page_error_body_1' => 'Please try again.',
        'page_error_body_2' => 'If the problem persists, keep the original message so the sender or operator can investigate.',
        'page_error_code_label' => 'Reference code',
        'page_download_unavailable_title' => 'This URL is not valid.',
        'page_download_unavailable_heading' => 'This URL is not valid.',
        'page_download_unavailable_body_1' => 'The link to this download has expired, been used already, or is no longer valid.',
        'page_download_unavailable_body_2' => '',
        'page_download_unavailable_body_3' => '',
        'detail_cycle_started' => 'The current cycle started on {datetime}.',
        'detail_last_confirm' => 'The last successful confirmation was recorded on {datetime}.',
        'detail_window_opens' => 'The confirmation window opens on {datetime}.',
        'detail_deadline' => 'The confirmation deadline for this cycle is {datetime}.',
        'detail_next_reminder' => 'The next reminder is scheduled for {datetime}.',
        'detail_window_opens_after' => '{duration} before the confirmation window opens.',
        'detail_window_length' => '{duration} for the confirmation window.',
        'detail_reminders_repeat' => 'Reminders repeat every {duration} while the window is open.',
        'detail_grace' => 'After the deadline, there is an additional grace period of {duration} before escalation is considered.',
        'detail_missed_required_one' => '1 missed cycle is required before escalation can trigger.',
        'detail_missed_required_other' => '{count} missed cycles are required before escalation can trigger.',
        'detail_missed_current_zero' => 'No missed cycles are currently recorded in state.',
        'detail_missed_current_one' => '1 missed cycle is currently recorded in state.',
        'detail_missed_current_other' => '{count} missed cycles are currently recorded in state.',
    ],
];
