<?php

declare(strict_types=1);

return [
    'locale' => 'es-ES',
    'html_lang' => 'es-ES',
    'date_template' => '{day} de {month} de {year} a las {time}',
    'months' => [
        1 => 'enero',
        2 => 'febrero',
        3 => 'marzo',
        4 => 'abril',
        5 => 'mayo',
        6 => 'junio',
        7 => 'julio',
        8 => 'agosto',
        9 => 'septiembre',
        10 => 'octubre',
        11 => 'noviembre',
        12 => 'diciembre',
    ],
    'duration_zero' => '0 segundos',
    'duration_pair_glue' => ' y ',
    'duration_middle_glue' => ', ',
    'duration_last_glue' => ' y ',
    'duration_units' => [
        'year' => ['one' => 'año', 'other' => 'años'],
        'month' => ['one' => 'mes', 'other' => 'meses'],
        'week' => ['one' => 'semana', 'other' => 'semanas'],
        'day' => ['one' => 'día', 'other' => 'días'],
        'hour' => ['one' => 'hora', 'other' => 'horas'],
        'minute' => ['one' => 'minuto', 'other' => 'minutos'],
        'second' => ['one' => 'segundo', 'other' => 'segundos'],
    ],
    'texts' => [
        'page_neutral_title' => 'Esta página no está disponible.',
        'page_neutral_heading' => 'Esta página no está disponible.',
        'page_neutral_body_1' => 'A través de esta URL no se muestra ninguna información adicional.',
        'page_neutral_body_2' => 'Ahora puede cerrar esta página.',
        'page_confirm_title' => '¿Sigue con vida?',
        'page_confirm_heading' => 'Por favor, comuníquese…',
        'page_confirm_intro' => 'Si todo está bien, por favor haga clic en el botón de abajo.',
        'page_confirm_button' => '¡Todo está bien!',
        'page_confirm_ok_title' => 'Confirmación guardada.',
        'page_confirm_ok_heading' => 'Gracias.',
        'page_confirm_ok_intro' => 'El ciclo se ha reiniciado…',
        'page_confirm_ok_details_heading' => 'Qué sucede ahora:',
        'page_ack_ok_title' => 'Acuse guardado.',
        'page_ack_ok_heading' => 'Gracias.',
        'page_ack_ok_body_1' => 'El mensaje ha quedado marcado como recibido.',
        'page_ack_ok_body_2' => 'No recibirá más correos electrónicos. El interruptor de hombre muerto ha sido desactivado.',
        'page_ack_ok_body_3' => 'Ahora siga, por favor, los deseos y las instrucciones que figuran en el correo electrónico recibido.',
        'page_ack_ok_body_4' => '¡Importante! Si el correo incluía un enlace de descarga, asegúrese de haber descargado ese documento.',
        'page_error_title' => 'Ahora mismo no ha funcionado.',
        'page_error_heading' => 'Ahora mismo no ha funcionado.',
        'page_error_body_1' => 'Vuelve a intentarlo.',
        'page_error_body_2' => 'Si el problema continúa, conserve el mensaje original para que el remitente o el operador puedan revisar el caso.',
        'page_error_code_label' => 'Código de referencia',
        'page_download_unavailable_title' => 'Esta URL no es válida.',
        'page_download_unavailable_heading' => 'Esta URL no es válida.',
        'page_download_unavailable_body_1' => 'El enlace a esta descarga ha caducado o ya no es válido.',
        'page_download_unavailable_body_2' => 'Conserve el mensaje original y vuelva a intentarlo más tarde si el enlace todavía debería ser válido…',
        'page_download_unavailable_body_3' => '',
        'detail_cycle_started' => 'El ciclo actual comenzó el {datetime}.',
        'detail_last_confirm' => 'La última confirmación correcta se registró el {datetime}.',
        'detail_window_opens' => 'La ventana de confirmación se abre el {datetime}.',
        'detail_deadline' => 'La fecha límite de confirmación para este ciclo es el {datetime}.',
        'detail_next_reminder' => 'El próximo recordatorio está previsto para el {datetime}.',
        'detail_window_opens_after' => 'La ventana de confirmación se abre dentro de {duration}.',
        'detail_window_length' => 'La ventana de confirmación permanece abierta durante {duration}.',
        'detail_reminders_repeat' => 'Mientras la ventana esté abierta, los recordatorios se repiten cada {duration}.',
        'detail_grace' => 'Después del plazo se aplica un periodo adicional de gracia de {duration} antes de considerar una escalada.',
        'detail_missed_required_one' => 'Se requiere 1 ciclo perdido antes de que pueda activarse una escalada.',
        'detail_missed_required_other' => 'Se requieren {count} ciclos perdidos antes de que pueda activarse una escalada.',
        'detail_missed_current_zero' => 'Actualmente no hay ciclos perdidos registrados.',
        'detail_missed_current_one' => 'Actualmente hay 1 ciclo perdido registrado.',
        'detail_missed_current_other' => 'Actualmente hay {count} ciclos perdidos registrados.',
    ],
];
