<?php

declare(strict_types=1);

return [
    'locale' => 'fr-FR',
    'html_lang' => 'fr-FR',
    'date_template' => '{day} {month} {year} à {time}',
    'months' => [
        1 => 'janvier',
        2 => 'février',
        3 => 'mars',
        4 => 'avril',
        5 => 'mai',
        6 => 'juin',
        7 => 'juillet',
        8 => 'août',
        9 => 'septembre',
        10 => 'octobre',
        11 => 'novembre',
        12 => 'décembre',
    ],
    'duration_zero' => '0 seconde',
    'duration_pair_glue' => ' et ',
    'duration_middle_glue' => ', ',
    'duration_last_glue' => ' et ',
    'duration_units' => [
        'year' => ['one' => 'an', 'other' => 'ans'],
        'month' => ['one' => 'mois', 'other' => 'mois'],
        'week' => ['one' => 'semaine', 'other' => 'semaines'],
        'day' => ['one' => 'jour', 'other' => 'jours'],
        'hour' => ['one' => 'heure', 'other' => 'heures'],
        'minute' => ['one' => 'minute', 'other' => 'minutes'],
        'second' => ['one' => 'seconde', 'other' => 'secondes'],
    ],
    'texts' => [
        'page_neutral_title' => 'Cette page n’est pas disponible.',
        'page_neutral_heading' => 'Cette page n’est pas disponible.',
        'page_neutral_body_1' => 'Aucune information supplémentaire n’est affichée via cette URL.',
        'page_neutral_body_2' => 'Vous pouvez maintenant fermer cette page.',
        'page_confirm_title' => 'Toujours en vie ?',
        'page_confirm_heading' => 'Veuillez vous signaler…',
        'page_confirm_intro' => 'Si tout va bien, veuillez cliquer sur le bouton ci-dessous.',
        'page_confirm_button' => 'Tout va bien !',
        'page_confirm_ok_title' => 'Confirmation enregistrée.',
        'page_confirm_ok_heading' => 'Merci.',
        'page_confirm_ok_intro' => 'Le cycle a été réinitialisé…',
        'page_confirm_ok_details_heading' => 'Ce qui se passe maintenant :',
        'page_ack_ok_title' => 'Accusé de réception enregistré.',
        'page_ack_ok_heading' => 'Merci.',
        'page_ack_ok_body_1' => 'Le message a été marqué comme reçu.',
        'page_ack_ok_body_2' => 'Vous ne recevrez plus aucun autre courriel. Le dispositif homme mort a été arrêté.',
        'page_ack_ok_body_3' => 'Veuillez maintenant suivre les souhaits et les instructions figurant dans le courriel reçu.',
        'page_ack_ok_body_4' => 'Important ! Si le courriel contenait un lien de téléchargement, assurez-vous d’avoir téléchargé ce document.',
        'page_error_title' => 'Cela n’a pas fonctionné pour le moment.',
        'page_error_heading' => 'Cela n’a pas fonctionné pour le moment.',
        'page_error_body_1' => 'Veuillez réessayer.',
        'page_error_body_2' => 'Si le problème persiste, conservez le message d’origine afin que l’expéditeur ou l’opérateur puisse vérifier la situation.',
        'page_error_code_label' => 'Code de référence',
        'page_download_unavailable_title' => 'Cette URL n’est pas valide.',
        'page_download_unavailable_heading' => 'Cette URL n’est pas valide.',
        'page_download_unavailable_body_1' => 'Le lien vers ce téléchargement a expiré ou n’est plus valide.',
        'page_download_unavailable_body_2' => 'Veuillez conserver le message d’origine et réessayer plus tard si le lien devrait encore être valide…',
        'page_download_unavailable_body_3' => '',
        'detail_cycle_started' => 'Le cycle actuel a commencé le {datetime}.',
        'detail_last_confirm' => 'La dernière confirmation réussie a été enregistrée le {datetime}.',
        'detail_window_opens' => 'La fenêtre de confirmation s’ouvre le {datetime}.',
        'detail_deadline' => 'La date limite de confirmation pour ce cycle est fixée au {datetime}.',
        'detail_next_reminder' => 'Le prochain rappel est prévu pour le {datetime}.',
        'detail_window_opens_after' => 'La fenêtre de confirmation s’ouvre dans {duration}.',
        'detail_window_length' => 'La fenêtre de confirmation reste ouverte pendant {duration}.',
        'detail_reminders_repeat' => 'Pendant que la fenêtre est ouverte, les rappels reviennent toutes les {duration}.',
        'detail_grace' => 'Après l’échéance, une période de grâce supplémentaire de {duration} s’applique avant qu’une escalade soit envisagée.',
        'detail_missed_required_one' => '1 cycle manqué est nécessaire avant qu’une escalade puisse être déclenchée.',
        'detail_missed_required_other' => '{count} cycles manqués sont nécessaires avant qu’une escalade puisse être déclenchée.',
        'detail_missed_current_zero' => 'Aucun cycle manqué n’est actuellement enregistré.',
        'detail_missed_current_one' => '1 cycle manqué est actuellement enregistré.',
        'detail_missed_current_other' => '{count} cycles manqués sont actuellement enregistrés.',
    ],
];
