<?php

declare(strict_types=1);

return [
    'locale' => 'it-IT',
    'html_lang' => 'it-IT',
    'date_template' => '{day} {month} {year} alle {time}',
    'months' => [
        1 => 'gennaio',
        2 => 'febbraio',
        3 => 'marzo',
        4 => 'aprile',
        5 => 'maggio',
        6 => 'giugno',
        7 => 'luglio',
        8 => 'agosto',
        9 => 'settembre',
        10 => 'ottobre',
        11 => 'novembre',
        12 => 'dicembre',
    ],
    'duration_zero' => '0 secondi',
    'duration_pair_glue' => ' e ',
    'duration_middle_glue' => ', ',
    'duration_last_glue' => ' e ',
    'duration_units' => [
        'year' => ['one' => 'anno', 'other' => 'anni'],
        'month' => ['one' => 'mese', 'other' => 'mesi'],
        'week' => ['one' => 'settimana', 'other' => 'settimane'],
        'day' => ['one' => 'giorno', 'other' => 'giorni'],
        'hour' => ['one' => 'ora', 'other' => 'ore'],
        'minute' => ['one' => 'minuto', 'other' => 'minuti'],
        'second' => ['one' => 'secondo', 'other' => 'secondi'],
    ],
    'texts' => [
        'page_neutral_title' => 'Questa pagina non è disponibile.',
        'page_neutral_heading' => 'Questa pagina non è disponibile.',
        'page_neutral_body_1' => 'Attraverso questo URL non vengono mostrate ulteriori informazioni.',
        'page_neutral_body_2' => 'Ora può chiudere questa pagina.',
        'page_confirm_title' => 'Ancora vivo?',
        'page_confirm_heading' => 'La preghiamo di farci sapere…',
        'page_confirm_intro' => 'Se va tutto bene, La preghiamo di cliccare il pulsante qui sotto.',
        'page_confirm_button' => 'Va tutto bene!',
        'page_confirm_ok_title' => 'Conferma salvata.',
        'page_confirm_ok_heading' => 'Grazie.',
        'page_confirm_ok_intro' => 'Il ciclo è stato reimpostato…',
        'page_confirm_ok_details_heading' => 'Che cosa succede adesso:',
        'page_ack_ok_title' => 'Conferma di ricezione salvata.',
        'page_ack_ok_heading' => 'Grazie.',
        'page_ack_ok_body_1' => 'Il messaggio è stato contrassegnato come ricevuto.',
        'page_ack_ok_body_2' => 'Non riceverà ulteriori email. Il dead man’s switch è stato disattivato.',
        'page_ack_ok_body_3' => 'La preghiamo ora di seguire i desideri e le istruzioni contenuti nell’email ricevuta.',
        'page_ack_ok_body_4' => 'Importante! Se l’email conteneva un link per il download, si assicuri di avere scaricato quel documento.',
        'page_error_title' => 'Al momento non ha funzionato.',
        'page_error_heading' => 'Al momento non ha funzionato.',
        'page_error_body_1' => 'Riprova.',
        'page_error_body_2' => 'Se il problema persiste, conservi il messaggio originale affinché il mittente o l’operatore possano verificare il caso.',
        'page_error_code_label' => 'Codice di riferimento',
        'page_download_unavailable_title' => 'Questo URL non è valido.',
        'page_download_unavailable_heading' => 'Questo URL non è valido.',
        'page_download_unavailable_body_1' => 'Il link a questo download è scaduto oppure non è più valido.',
        'page_download_unavailable_body_2' => 'Conservi il messaggio originale e riprovi più tardi se il link dovrebbe essere ancora valido…',
        'page_download_unavailable_body_3' => '',
        'detail_cycle_started' => 'Il ciclo corrente è iniziato il {datetime}.',
        'detail_last_confirm' => 'L’ultima conferma riuscita è stata registrata il {datetime}.',
        'detail_window_opens' => 'La finestra di conferma si apre il {datetime}.',
        'detail_deadline' => 'La scadenza della conferma per questo ciclo è il {datetime}.',
        'detail_next_reminder' => 'Il prossimo promemoria è previsto per il {datetime}.',
        'detail_window_opens_after' => 'La finestra di conferma si apre tra {duration}.',
        'detail_window_length' => 'La finestra di conferma rimane aperta per {duration}.',
        'detail_reminders_repeat' => 'Finché la finestra è aperta, i promemoria si ripetono ogni {duration}.',
        'detail_grace' => 'Dopo la scadenza si applica un ulteriore periodo di tolleranza di {duration} prima che venga presa in considerazione un’escalation.',
        'detail_missed_required_one' => 'È necessario 1 ciclo mancato prima che possa essere avviata un’escalation.',
        'detail_missed_required_other' => 'Sono necessari {count} cicli mancati prima che possa essere avviata un’escalation.',
        'detail_missed_current_zero' => 'Al momento non risultano cicli mancati registrati.',
        'detail_missed_current_one' => 'Al momento risulta registrato 1 ciclo mancato.',
        'detail_missed_current_other' => 'Al momento risultano registrati {count} cicli mancati.',
    ],
];
